### ISSUE TITLE
Not able to install in Python 3.7

### ISSUE THREAD

**Issue by divyankraina** [google/transitfeed#493] opened 2019-10-26 03:47 UTC
Here's the error received while trying a fresh install:

Running command git clone -q https://github.com/google/transitfeed.git 'C:\Users\divya\AppData\Local\Temp\pip-req-build-gzltgzss'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\divya\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\divya\\AppData\\Local\\Temp\\pip-req-build-gzltgzss\\setup.py'"'"'; __file__='"'"'C:\\Users\\divya\\AppData\\Local\\Temp\\pip-req-build-gzltgzss\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\divya\AppData\Local\Temp\pip-req-build-gzltgzss\pip-egg-info'
         cwd: C:\Users\divya\AppData\Local\Temp\pip-req-build-gzltgzss\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\divya\AppData\Local\Temp\pip-req-build-gzltgzss\setup.py", line 29, in <module>
        from transitfeed import __version__ as VERSION
      File "C:\Users\divya\AppData\Local\Temp\pip-req-build-gzltgzss\transitfeed\__init__.py", line 67, in <module>
        from .util import *
      File "C:\Users\divya\AppData\Local\Temp\pip-req-build-gzltgzss\transitfeed\util.py", line 29, in <module>
        import urllib2
    ModuleNotFoundError: No module named 'urllib2'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by pecalleja** [comment] 2019-10-26 17:54
this error is because the python 3 porting of this project is not ready (https://github.com/google/transitfeed/pull/491). there is a fork with python 3 branch. you could try clone the fork (https://github.com/pecalleja/transitfeed), change to `python3` branch and try to install (no tested in windows).

**Comment by jarondl** [comment] 2019-10-28 20:04
duplicate of #412

**Closed by jarondl** 2019-10-28 20:04 UTC
