### ISSUE TITLE
Where is .exe file?

### ISSUE THREAD

**Issue by margat78** [google/transitfeed#502] opened 2019-12-09 11:04 UTC
_Drag a GTFS zip file or directory onto feedvalidator.exe. A window will pop up with the result of the validation test:_

I can't find Windows standalone version.

**Comment by barbeau** [comment] 2019-12-09 15:29
@margat78 Looks like the last release with a Windows binary was 1.2.15:
https://github.com/google/transitfeed/releases/tag/1.2.15

**Comment by KristjanESPERANTO** [comment] 2019-12-09 16:45
Duplicate of #446

**Comment by barbeau** [comment] 2019-12-09 16:47
Thanks @KristjanESPERANTO. Closing as duplicate of #446.

**Closed by barbeau** 2019-12-09 16:47 UTC
Labels: duplicate
